// Daftar universitas negeri Indonesia + jurusan populer + estimasi passing grade SNBT 2026
// Data ini adalah estimasi berdasarkan data tahun sebelumnya

const UNIVERSITAS_DATA = [
  {
    id: 'ui',
    nama: 'Universitas Indonesia',
    singkatan: 'UI',
    lokasi: 'Depok, Jawa Barat',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 730 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 710 },
      { nama: 'Ilmu Komputer', rumpun: 'Saintek', passing_grade: 700 },
      { nama: 'Teknik Elektro', rumpun: 'Saintek', passing_grade: 680 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 670 },
      { nama: 'Teknik Kimia', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Arsitektur', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Sistem Informasi', rumpun: 'Saintek', passing_grade: 680 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 700 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 690 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 680 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 680 },
      { nama: 'Ilmu Komunikasi', rumpun: 'Soshum', passing_grade: 670 },
      { nama: 'Hubungan Internasional', rumpun: 'Soshum', passing_grade: 660 },
      { nama: 'Administrasi Bisnis', rumpun: 'Soshum', passing_grade: 640 },
      { nama: 'Ilmu Politik', rumpun: 'Soshum', passing_grade: 630 },
      { nama: 'Sastra Inggris', rumpun: 'Soshum', passing_grade: 620 },
    ],
  },
  {
    id: 'itb',
    nama: 'Institut Teknologi Bandung',
    singkatan: 'ITB',
    lokasi: 'Bandung, Jawa Barat',
    jurusan: [
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 720 },
      { nama: 'Teknik Elektro', rumpun: 'Saintek', passing_grade: 700 },
      { nama: 'Teknik Mesin', rumpun: 'Saintek', passing_grade: 680 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 670 },
      { nama: 'Teknik Kimia', rumpun: 'Saintek', passing_grade: 670 },
      { nama: 'Arsitektur', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Matematika', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Fisika', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Teknik Lingkungan', rumpun: 'Saintek', passing_grade: 630 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 680 },
      { nama: 'Desain Komunikasi Visual', rumpun: 'Saintek', passing_grade: 650 },
    ],
  },
  {
    id: 'ugm',
    nama: 'Universitas Gadjah Mada',
    singkatan: 'UGM',
    lokasi: 'Yogyakarta',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 720 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 690 },
      { nama: 'Teknik Elektro', rumpun: 'Saintek', passing_grade: 670 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 670 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Teknik Kimia', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Arsitektur', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Ilmu Komputer', rumpun: 'Saintek', passing_grade: 680 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 680 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 670 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 660 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 670 },
      { nama: 'Ilmu Komunikasi', rumpun: 'Soshum', passing_grade: 650 },
      { nama: 'Hubungan Internasional', rumpun: 'Soshum', passing_grade: 650 },
      { nama: 'Ilmu Ekonomi', rumpun: 'Soshum', passing_grade: 640 },
      { nama: 'Kedokteran Gigi', rumpun: 'Saintek', passing_grade: 680 },
    ],
  },
  {
    id: 'ipb',
    nama: 'Institut Pertanian Bogor',
    singkatan: 'IPB',
    lokasi: 'Bogor, Jawa Barat',
    jurusan: [
      { nama: 'Ilmu Komputer', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Statistika', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Teknologi Pangan', rumpun: 'Saintek', passing_grade: 630 },
      { nama: 'Teknik Sipil & Lingkungan', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Agribisnis', rumpun: 'Soshum', passing_grade: 600 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 630 },
      { nama: 'Kedokteran Hewan', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Biokimia', rumpun: 'Saintek', passing_grade: 600 },
      { nama: 'Gizi', rumpun: 'Saintek', passing_grade: 610 },
      { nama: 'Kimia', rumpun: 'Saintek', passing_grade: 580 },
    ],
  },
  {
    id: 'unpad',
    nama: 'Universitas Padjadjaran',
    singkatan: 'Unpad',
    lokasi: 'Bandung, Jawa Barat',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 700 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 660 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 650 },
      { nama: 'Ilmu Komunikasi', rumpun: 'Soshum', passing_grade: 650 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 640 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 640 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Hubungan Internasional', rumpun: 'Soshum', passing_grade: 640 },
      { nama: 'Kedokteran Gigi', rumpun: 'Saintek', passing_grade: 670 },
    ],
  },
  {
    id: 'unair',
    nama: 'Universitas Airlangga',
    singkatan: 'Unair',
    lokasi: 'Surabaya, Jawa Timur',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 700 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Kedokteran Hewan', rumpun: 'Saintek', passing_grade: 600 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 650 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 640 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 640 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 630 },
      { nama: 'Ilmu Komunikasi', rumpun: 'Soshum', passing_grade: 620 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Kedokteran Gigi', rumpun: 'Saintek', passing_grade: 660 },
    ],
  },
  {
    id: 'undip',
    nama: 'Universitas Diponegoro',
    singkatan: 'Undip',
    lokasi: 'Semarang, Jawa Tengah',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 680 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 630 },
      { nama: 'Teknik Elektro', rumpun: 'Saintek', passing_grade: 630 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 640 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 630 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 620 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 630 },
      { nama: 'Ilmu Komunikasi', rumpun: 'Soshum', passing_grade: 610 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 630 },
    ],
  },
  {
    id: 'ub',
    nama: 'Universitas Brawijaya',
    singkatan: 'UB',
    lokasi: 'Malang, Jawa Timur',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 670 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Teknik Elektro', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 630 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 630 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 620 },
      { nama: 'Ilmu Komunikasi', rumpun: 'Soshum', passing_grade: 610 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 610 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 620 },
    ],
  },
  {
    id: 'its',
    nama: 'Institut Teknologi Sepuluh Nopember',
    singkatan: 'ITS',
    lokasi: 'Surabaya, Jawa Timur',
    jurusan: [
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 670 },
      { nama: 'Teknik Elektro', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Teknik Mesin', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Teknik Kimia', rumpun: 'Saintek', passing_grade: 630 },
      { nama: 'Sistem Informasi', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Arsitektur', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Desain Produk', rumpun: 'Saintek', passing_grade: 600 },
      { nama: 'Statistika', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Teknik Lingkungan', rumpun: 'Saintek', passing_grade: 590 },
    ],
  },
  {
    id: 'uns',
    nama: 'Universitas Sebelas Maret',
    singkatan: 'UNS',
    lokasi: 'Surakarta, Jawa Tengah',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 620 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 610 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 610 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 610 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 590 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 600 },
      { nama: 'Ilmu Komunikasi', rumpun: 'Soshum', passing_grade: 600 },
    ],
  },
  {
    id: 'usu',
    nama: 'Universitas Sumatera Utara',
    singkatan: 'USU',
    lokasi: 'Medan, Sumatera Utara',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 620 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 610 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 620 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 600 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 600 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 580 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 600 },
      { nama: 'Ilmu Komunikasi', rumpun: 'Soshum', passing_grade: 590 },
    ],
  },
  {
    id: 'unhas',
    nama: 'Universitas Hasanuddin',
    singkatan: 'Unhas',
    lokasi: 'Makassar, Sulawesi Selatan',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 660 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 610 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 600 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 620 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 600 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 590 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 580 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 590 },
      { nama: 'Kedokteran Gigi', rumpun: 'Saintek', passing_grade: 630 },
    ],
  },
  {
    id: 'upi',
    nama: 'Universitas Pendidikan Indonesia',
    singkatan: 'UPI',
    lokasi: 'Bandung, Jawa Barat',
    jurusan: [
      { nama: 'Pendidikan Matematika', rumpun: 'Saintek', passing_grade: 600 },
      { nama: 'Pendidikan Bahasa Inggris', rumpun: 'Soshum', passing_grade: 590 },
      { nama: 'Ilmu Komputer', rumpun: 'Saintek', passing_grade: 610 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 600 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 600 },
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 630 },
      { nama: 'Pendidikan Guru SD', rumpun: 'Soshum', passing_grade: 570 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 580 },
    ],
  },
  {
    id: 'uny',
    nama: 'Universitas Negeri Yogyakarta',
    singkatan: 'UNY',
    lokasi: 'Yogyakarta',
    jurusan: [
      { nama: 'Pendidikan Bahasa Inggris', rumpun: 'Soshum', passing_grade: 580 },
      { nama: 'Pendidikan Matematika', rumpun: 'Saintek', passing_grade: 570 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 580 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 570 },
      { nama: 'Ilmu Komputer', rumpun: 'Saintek', passing_grade: 580 },
      { nama: 'Pendidikan Guru SD', rumpun: 'Soshum', passing_grade: 550 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 560 },
    ],
  },
  {
    id: 'unnes',
    nama: 'Universitas Negeri Semarang',
    singkatan: 'UNNES',
    lokasi: 'Semarang, Jawa Tengah',
    jurusan: [
      { nama: 'Pendidikan Matematika', rumpun: 'Saintek', passing_grade: 560 },
      { nama: 'Pendidikan Bahasa Inggris', rumpun: 'Soshum', passing_grade: 560 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 570 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 570 },
      { nama: 'Ilmu Komputer', rumpun: 'Saintek', passing_grade: 570 },
      { nama: 'Psikologi', rumpun: 'Soshum', passing_grade: 560 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 550 },
    ],
  },
  {
    id: 'unila',
    nama: 'Universitas Lampung',
    singkatan: 'Unila',
    lokasi: 'Bandar Lampung, Lampung',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 630 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 580 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 580 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 570 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 560 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 570 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 550 },
    ],
  },
  {
    id: 'unsri',
    nama: 'Universitas Sriwijaya',
    singkatan: 'Unsri',
    lokasi: 'Palembang, Sumatera Selatan',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 580 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 580 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 560 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 570 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 550 },
    ],
  },
  {
    id: 'unand',
    nama: 'Universitas Andalas',
    singkatan: 'Unand',
    lokasi: 'Padang, Sumatera Barat',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 590 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 590 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 590 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 570 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 560 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 550 },
    ],
  },
  {
    id: 'udayana',
    nama: 'Universitas Udayana',
    singkatan: 'Unud',
    lokasi: 'Denpasar, Bali',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 650 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 590 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 580 },
      { nama: 'Teknik Informatika', rumpun: 'Saintek', passing_grade: 580 },
      { nama: 'Farmasi', rumpun: 'Saintek', passing_grade: 580 },
      { nama: 'Akuntansi', rumpun: 'Soshum', passing_grade: 560 },
      { nama: 'Pariwisata', rumpun: 'Soshum', passing_grade: 560 },
    ],
  },
  {
    id: 'unsyiah',
    nama: 'Universitas Syiah Kuala',
    singkatan: 'USK',
    lokasi: 'Banda Aceh, Aceh',
    jurusan: [
      { nama: 'Pendidikan Dokter', rumpun: 'Saintek', passing_grade: 640 },
      { nama: 'Kedokteran Hewan', rumpun: 'Saintek', passing_grade: 586 },
      { nama: 'Teknik Sipil', rumpun: 'Saintek', passing_grade: 570 },
      { nama: 'Hukum', rumpun: 'Soshum', passing_grade: 570 },
      { nama: 'Manajemen', rumpun: 'Soshum', passing_grade: 550 },
      { nama: 'Teknik Mesin', rumpun: 'Saintek', passing_grade: 555 },
      { nama: 'Kedokteran Gigi', rumpun: 'Saintek', passing_grade: 620 },
    ],
  },
];

export default UNIVERSITAS_DATA;
